version: 1.0
provider:
  name: openfaas
functions:
  openfaas-inceptionfeed:
    lang: python3
    handler: ./openfaas-inceptionfeed
    image: servernull/openfaas-inceptionfeed:0.1.0
    environment:
      read_timeout: 660
      write_timeout: 660
      exec_timeout: 660
